const std = @import("std");

const TestEntry = struct {
    name: []const u8,
    path: []const u8,
};

// Authoritative list of spec test ELFs the runner will spawn. Each
// entry corresponds to a `[test NN]` tag in docs/kernel/specv3.md.
// Manifest order is also spawn order; tests that conflict on global
// resources should be ordered serially here. New tests: add a file
// under tests/ then add an entry below.
const test_entries = [_]TestEntry{
    .{ .name = "ack_01", .path = "tests/ack_01.zig" },
    .{ .name = "ack_02", .path = "tests/ack_02.zig" },
    .{ .name = "ack_03", .path = "tests/ack_03.zig" },
    .{ .name = "ack_04", .path = "tests/ack_04.zig" },
    .{ .name = "ack_05", .path = "tests/ack_05.zig" },
    .{ .name = "ack_06", .path = "tests/ack_06.zig" },
    .{ .name = "ack_07", .path = "tests/ack_07.zig" },
    .{ .name = "ack_08", .path = "tests/ack_08.zig" },
    .{ .name = "acquire_ecs_01", .path = "tests/acquire_ecs_01.zig" },
    .{ .name = "acquire_ecs_02", .path = "tests/acquire_ecs_02.zig" },
    .{ .name = "acquire_ecs_03", .path = "tests/acquire_ecs_03.zig" },
    .{ .name = "acquire_ecs_04", .path = "tests/acquire_ecs_04.zig" },
    .{ .name = "acquire_ecs_05", .path = "tests/acquire_ecs_05.zig" },
    .{ .name = "acquire_ecs_06", .path = "tests/acquire_ecs_06.zig" },
    .{ .name = "acquire_ecs_07", .path = "tests/acquire_ecs_07.zig" },
    .{ .name = "acquire_vars_01", .path = "tests/acquire_vars_01.zig" },
    .{ .name = "acquire_vars_02", .path = "tests/acquire_vars_02.zig" },
    .{ .name = "acquire_vars_03", .path = "tests/acquire_vars_03.zig" },
    .{ .name = "acquire_vars_04", .path = "tests/acquire_vars_04.zig" },
    .{ .name = "acquire_vars_05", .path = "tests/acquire_vars_05.zig" },
    .{ .name = "acquire_vars_06", .path = "tests/acquire_vars_06.zig" },
    .{ .name = "acquire_vars_07", .path = "tests/acquire_vars_07.zig" },
    .{ .name = "affinity_01", .path = "tests/affinity_01.zig" },
    .{ .name = "affinity_02", .path = "tests/affinity_02.zig" },
    .{ .name = "affinity_03", .path = "tests/affinity_03.zig" },
    .{ .name = "affinity_04", .path = "tests/affinity_04.zig" },
    .{ .name = "affinity_05", .path = "tests/affinity_05.zig" },
    .{ .name = "affinity_06", .path = "tests/affinity_06.zig" },
    .{ .name = "bind_event_route_01", .path = "tests/bind_event_route_01.zig" },
    .{ .name = "bind_event_route_02", .path = "tests/bind_event_route_02.zig" },
    .{ .name = "bind_event_route_03", .path = "tests/bind_event_route_03.zig" },
    .{ .name = "bind_event_route_05", .path = "tests/bind_event_route_05.zig" },
    .{ .name = "bind_event_route_06", .path = "tests/bind_event_route_06.zig" },
    .{ .name = "bind_event_route_07", .path = "tests/bind_event_route_07.zig" },
    .{ .name = "bind_event_route_08", .path = "tests/bind_event_route_08.zig" },
    .{ .name = "bind_event_route_09", .path = "tests/bind_event_route_09.zig" },
    .{ .name = "bind_event_route_10", .path = "tests/bind_event_route_10.zig" },
    .{ .name = "clear_event_route_01", .path = "tests/clear_event_route_01.zig" },
    .{ .name = "clear_event_route_02", .path = "tests/clear_event_route_02.zig" },
    .{ .name = "clear_event_route_03", .path = "tests/clear_event_route_03.zig" },
    .{ .name = "clear_event_route_04", .path = "tests/clear_event_route_04.zig" },
    .{ .name = "clear_event_route_05", .path = "tests/clear_event_route_05.zig" },
    .{ .name = "clear_event_route_06", .path = "tests/clear_event_route_06.zig" },
    .{ .name = "clear_event_route_07", .path = "tests/clear_event_route_07.zig" },
    .{ .name = "create_capability_domain_01", .path = "tests/create_capability_domain_01.zig" },
    .{ .name = "create_capability_domain_02", .path = "tests/create_capability_domain_02.zig" },
    .{ .name = "create_capability_domain_03", .path = "tests/create_capability_domain_03.zig" },
    .{ .name = "create_capability_domain_04", .path = "tests/create_capability_domain_04.zig" },
    .{ .name = "create_capability_domain_05", .path = "tests/create_capability_domain_05.zig" },
    .{ .name = "create_capability_domain_06", .path = "tests/create_capability_domain_06.zig" },
    .{ .name = "create_capability_domain_07", .path = "tests/create_capability_domain_07.zig" },
    .{ .name = "create_capability_domain_08", .path = "tests/create_capability_domain_08.zig" },
    .{ .name = "create_capability_domain_09", .path = "tests/create_capability_domain_09.zig" },
    .{ .name = "create_capability_domain_10", .path = "tests/create_capability_domain_10.zig" },
    .{ .name = "create_capability_domain_11", .path = "tests/create_capability_domain_11.zig" },
    .{ .name = "create_capability_domain_12", .path = "tests/create_capability_domain_12.zig" },
    .{ .name = "create_capability_domain_13", .path = "tests/create_capability_domain_13.zig" },
    .{ .name = "create_capability_domain_14", .path = "tests/create_capability_domain_14.zig" },
    .{ .name = "create_capability_domain_15", .path = "tests/create_capability_domain_15.zig" },
    .{ .name = "create_capability_domain_16", .path = "tests/create_capability_domain_16.zig" },
    .{ .name = "create_capability_domain_17", .path = "tests/create_capability_domain_17.zig" },
    .{ .name = "create_capability_domain_18", .path = "tests/create_capability_domain_18.zig" },
    .{ .name = "create_capability_domain_19", .path = "tests/create_capability_domain_19.zig" },
    .{ .name = "create_capability_domain_20", .path = "tests/create_capability_domain_20.zig" },
    .{ .name = "create_capability_domain_21", .path = "tests/create_capability_domain_21.zig" },
    .{ .name = "create_capability_domain_22", .path = "tests/create_capability_domain_22.zig" },
    .{ .name = "create_capability_domain_23", .path = "tests/create_capability_domain_23.zig" },
    .{ .name = "create_capability_domain_24", .path = "tests/create_capability_domain_24.zig" },
    .{ .name = "create_capability_domain_25", .path = "tests/create_capability_domain_25.zig" },
    .{ .name = "create_capability_domain_26", .path = "tests/create_capability_domain_26.zig" },
    .{ .name = "create_capability_domain_27", .path = "tests/create_capability_domain_27.zig" },
    .{ .name = "create_capability_domain_28", .path = "tests/create_capability_domain_28.zig" },
    .{ .name = "create_capability_domain_29", .path = "tests/create_capability_domain_29.zig" },
    .{ .name = "create_execution_context_01", .path = "tests/create_execution_context_01.zig" },
    .{ .name = "create_execution_context_02", .path = "tests/create_execution_context_02.zig" },
    .{ .name = "create_execution_context_03", .path = "tests/create_execution_context_03.zig" },
    .{ .name = "create_execution_context_04", .path = "tests/create_execution_context_04.zig" },
    .{ .name = "create_execution_context_05", .path = "tests/create_execution_context_05.zig" },
    .{ .name = "create_execution_context_06", .path = "tests/create_execution_context_06.zig" },
    .{ .name = "create_execution_context_07", .path = "tests/create_execution_context_07.zig" },
    .{ .name = "create_execution_context_08", .path = "tests/create_execution_context_08.zig" },
    .{ .name = "create_execution_context_09", .path = "tests/create_execution_context_09.zig" },
    .{ .name = "create_execution_context_10", .path = "tests/create_execution_context_10.zig" },
    .{ .name = "create_execution_context_11", .path = "tests/create_execution_context_11.zig" },
    .{ .name = "create_execution_context_12", .path = "tests/create_execution_context_12.zig" },
    .{ .name = "create_execution_context_13", .path = "tests/create_execution_context_13.zig" },
    .{ .name = "create_execution_context_14", .path = "tests/create_execution_context_14.zig" },
    .{ .name = "create_page_frame_01", .path = "tests/create_page_frame_01.zig" },
    .{ .name = "create_page_frame_02", .path = "tests/create_page_frame_02.zig" },
    .{ .name = "create_page_frame_03", .path = "tests/create_page_frame_03.zig" },
    .{ .name = "create_page_frame_04", .path = "tests/create_page_frame_04.zig" },
    .{ .name = "create_page_frame_05", .path = "tests/create_page_frame_05.zig" },
    .{ .name = "create_page_frame_06", .path = "tests/create_page_frame_06.zig" },
    .{ .name = "create_page_frame_07", .path = "tests/create_page_frame_07.zig" },
    .{ .name = "create_page_frame_08", .path = "tests/create_page_frame_08.zig" },
    .{ .name = "create_page_frame_09", .path = "tests/create_page_frame_09.zig" },
    .{ .name = "create_page_frame_10", .path = "tests/create_page_frame_10.zig" },
    .{ .name = "create_port_01", .path = "tests/create_port_01.zig" },
    .{ .name = "create_port_02", .path = "tests/create_port_02.zig" },
    .{ .name = "create_port_03", .path = "tests/create_port_03.zig" },
    .{ .name = "create_port_04", .path = "tests/create_port_04.zig" },
    .{ .name = "create_var_01", .path = "tests/create_var_01.zig" },
    .{ .name = "create_var_02", .path = "tests/create_var_02.zig" },
    .{ .name = "create_var_03", .path = "tests/create_var_03.zig" },
    .{ .name = "create_var_04", .path = "tests/create_var_04.zig" },
    .{ .name = "create_var_05", .path = "tests/create_var_05.zig" },
    .{ .name = "create_var_06", .path = "tests/create_var_06.zig" },
    .{ .name = "create_var_07", .path = "tests/create_var_07.zig" },
    .{ .name = "create_var_08", .path = "tests/create_var_08.zig" },
    .{ .name = "create_var_09", .path = "tests/create_var_09.zig" },
    .{ .name = "create_var_10", .path = "tests/create_var_10.zig" },
    .{ .name = "create_var_11", .path = "tests/create_var_11.zig" },
    .{ .name = "create_var_12", .path = "tests/create_var_12.zig" },
    .{ .name = "create_var_13", .path = "tests/create_var_13.zig" },
    .{ .name = "create_var_14", .path = "tests/create_var_14.zig" },
    .{ .name = "create_var_15", .path = "tests/create_var_15.zig" },
    .{ .name = "create_var_16", .path = "tests/create_var_16.zig" },
    .{ .name = "create_var_17", .path = "tests/create_var_17.zig" },
    .{ .name = "create_var_18", .path = "tests/create_var_18.zig" },
    .{ .name = "create_var_19", .path = "tests/create_var_19.zig" },
    .{ .name = "create_var_20", .path = "tests/create_var_20.zig" },
    .{ .name = "create_var_21", .path = "tests/create_var_21.zig" },
    .{ .name = "create_var_22", .path = "tests/create_var_22.zig" },
    .{ .name = "create_vcpu_01", .path = "tests/create_vcpu_01.zig" },
    .{ .name = "create_vcpu_02", .path = "tests/create_vcpu_02.zig" },
    .{ .name = "create_vcpu_03", .path = "tests/create_vcpu_03.zig" },
    .{ .name = "create_vcpu_04", .path = "tests/create_vcpu_04.zig" },
    .{ .name = "create_vcpu_05", .path = "tests/create_vcpu_05.zig" },
    .{ .name = "create_vcpu_06", .path = "tests/create_vcpu_06.zig" },
    .{ .name = "create_vcpu_07", .path = "tests/create_vcpu_07.zig" },
    .{ .name = "create_vcpu_08", .path = "tests/create_vcpu_08.zig" },
    .{ .name = "create_vcpu_09", .path = "tests/create_vcpu_09.zig" },
    .{ .name = "create_vcpu_10", .path = "tests/create_vcpu_10.zig" },
    .{ .name = "create_vcpu_11", .path = "tests/create_vcpu_11.zig" },
    .{ .name = "create_vcpu_12", .path = "tests/create_vcpu_12.zig" },
    .{ .name = "create_virtual_machine_01", .path = "tests/create_virtual_machine_01.zig" },
    .{ .name = "create_virtual_machine_02", .path = "tests/create_virtual_machine_02.zig" },
    .{ .name = "create_virtual_machine_03", .path = "tests/create_virtual_machine_03.zig" },
    .{ .name = "create_virtual_machine_04", .path = "tests/create_virtual_machine_04.zig" },
    .{ .name = "create_virtual_machine_05", .path = "tests/create_virtual_machine_05.zig" },
    .{ .name = "create_virtual_machine_06", .path = "tests/create_virtual_machine_06.zig" },
    .{ .name = "create_virtual_machine_07", .path = "tests/create_virtual_machine_07.zig" },
    .{ .name = "create_virtual_machine_08", .path = "tests/create_virtual_machine_08.zig" },
    .{ .name = "create_virtual_machine_09", .path = "tests/create_virtual_machine_09.zig" },
    .{ .name = "delete_01", .path = "tests/delete_01.zig" },
    .{ .name = "delete_02", .path = "tests/delete_02.zig" },
    .{ .name = "delete_03", .path = "tests/delete_03.zig" },
    .{ .name = "device_irq_01", .path = "tests/device_irq_01.zig" },
    .{ .name = "device_irq_02", .path = "tests/device_irq_02.zig" },
    .{ .name = "device_irq_03", .path = "tests/device_irq_03.zig" },
    .{ .name = "device_irq_04", .path = "tests/device_irq_04.zig" },
    .{ .name = "futex_wait_change_01", .path = "tests/futex_wait_change_01.zig" },
    .{ .name = "futex_wait_change_02", .path = "tests/futex_wait_change_02.zig" },
    .{ .name = "futex_wait_val_01", .path = "tests/futex_wait_val_01.zig" },
    .{ .name = "futex_wait_val_02", .path = "tests/futex_wait_val_02.zig" },
    .{ .name = "futex_wake_01", .path = "tests/futex_wake_01.zig" },
    .{ .name = "futex_wake_03", .path = "tests/futex_wake_03.zig" },
    .{ .name = "futex_wake_04", .path = "tests/futex_wake_04.zig" },
    .{ .name = "handle_attachments_01", .path = "tests/handle_attachments_01.zig" },
    .{ .name = "handle_attachments_02", .path = "tests/handle_attachments_02.zig" },
    .{ .name = "handle_attachments_03", .path = "tests/handle_attachments_03.zig" },
    .{ .name = "idc_read_01", .path = "tests/idc_read_01.zig" },
    .{ .name = "idc_read_02", .path = "tests/idc_read_02.zig" },
    .{ .name = "idc_read_03", .path = "tests/idc_read_03.zig" },
    .{ .name = "idc_read_04", .path = "tests/idc_read_04.zig" },
    .{ .name = "idc_read_05", .path = "tests/idc_read_05.zig" },
    .{ .name = "idc_read_06", .path = "tests/idc_read_06.zig" },
    .{ .name = "idc_read_07", .path = "tests/idc_read_07.zig" },
    .{ .name = "idc_read_08", .path = "tests/idc_read_08.zig" },
    .{ .name = "idc_write_01", .path = "tests/idc_write_01.zig" },
    .{ .name = "idc_write_02", .path = "tests/idc_write_02.zig" },
    .{ .name = "idc_write_03", .path = "tests/idc_write_03.zig" },
    .{ .name = "idc_write_04", .path = "tests/idc_write_04.zig" },
    .{ .name = "idc_write_05", .path = "tests/idc_write_05.zig" },
    .{ .name = "idc_write_06", .path = "tests/idc_write_06.zig" },
    .{ .name = "idc_write_07", .path = "tests/idc_write_07.zig" },
    .{ .name = "idc_write_08", .path = "tests/idc_write_08.zig" },
    .{ .name = "map_guest_01", .path = "tests/map_guest_01.zig" },
    .{ .name = "map_guest_02", .path = "tests/map_guest_02.zig" },
    .{ .name = "map_guest_03", .path = "tests/map_guest_03.zig" },
    .{ .name = "map_guest_04", .path = "tests/map_guest_04.zig" },
    .{ .name = "map_guest_05", .path = "tests/map_guest_05.zig" },
    .{ .name = "map_guest_06", .path = "tests/map_guest_06.zig" },
    .{ .name = "map_guest_07", .path = "tests/map_guest_07.zig" },
    .{ .name = "map_mmio_01", .path = "tests/map_mmio_01.zig" },
    .{ .name = "map_mmio_02", .path = "tests/map_mmio_02.zig" },
    .{ .name = "map_mmio_03", .path = "tests/map_mmio_03.zig" },
    .{ .name = "map_mmio_04", .path = "tests/map_mmio_04.zig" },
    .{ .name = "map_mmio_05", .path = "tests/map_mmio_05.zig" },
    .{ .name = "map_mmio_06", .path = "tests/map_mmio_06.zig" },
    .{ .name = "map_mmio_07", .path = "tests/map_mmio_07.zig" },
    .{ .name = "map_mmio_08", .path = "tests/map_mmio_08.zig" },
    .{ .name = "map_mmio_09", .path = "tests/map_mmio_09.zig" },
    .{ .name = "map_pf_01", .path = "tests/map_pf_01.zig" },
    .{ .name = "map_pf_02", .path = "tests/map_pf_02.zig" },
    .{ .name = "map_pf_03", .path = "tests/map_pf_03.zig" },
    .{ .name = "map_pf_04", .path = "tests/map_pf_04.zig" },
    .{ .name = "map_pf_05", .path = "tests/map_pf_05.zig" },
    .{ .name = "map_pf_06", .path = "tests/map_pf_06.zig" },
    .{ .name = "map_pf_07", .path = "tests/map_pf_07.zig" },
    .{ .name = "map_pf_08", .path = "tests/map_pf_08.zig" },
    .{ .name = "map_pf_09", .path = "tests/map_pf_09.zig" },
    .{ .name = "map_pf_10", .path = "tests/map_pf_10.zig" },
    .{ .name = "map_pf_11", .path = "tests/map_pf_11.zig" },
    .{ .name = "map_pf_12", .path = "tests/map_pf_12.zig" },
    .{ .name = "map_pf_13", .path = "tests/map_pf_13.zig" },
    .{ .name = "map_pf_14", .path = "tests/map_pf_14.zig" },
    .{ .name = "perfmon_info_01", .path = "tests/perfmon_info_01.zig" },
    .{ .name = "perfmon_info_02", .path = "tests/perfmon_info_02.zig" },
    .{ .name = "perfmon_info_03", .path = "tests/perfmon_info_03.zig" },
    .{ .name = "perfmon_info_04", .path = "tests/perfmon_info_04.zig" },
    .{ .name = "perfmon_read_01", .path = "tests/perfmon_read_01.zig" },
    .{ .name = "perfmon_read_02", .path = "tests/perfmon_read_02.zig" },
    .{ .name = "perfmon_read_03", .path = "tests/perfmon_read_03.zig" },
    .{ .name = "perfmon_read_04", .path = "tests/perfmon_read_04.zig" },
    .{ .name = "perfmon_read_05", .path = "tests/perfmon_read_05.zig" },
    .{ .name = "perfmon_read_06", .path = "tests/perfmon_read_06.zig" },
    .{ .name = "perfmon_read_07", .path = "tests/perfmon_read_07.zig" },
    .{ .name = "perfmon_start_01", .path = "tests/perfmon_start_01.zig" },
    .{ .name = "perfmon_start_02", .path = "tests/perfmon_start_02.zig" },
    .{ .name = "perfmon_start_03", .path = "tests/perfmon_start_03.zig" },
    .{ .name = "perfmon_start_04", .path = "tests/perfmon_start_04.zig" },
    .{ .name = "perfmon_start_05", .path = "tests/perfmon_start_05.zig" },
    .{ .name = "perfmon_start_06", .path = "tests/perfmon_start_06.zig" },
    .{ .name = "perfmon_start_07", .path = "tests/perfmon_start_07.zig" },
    .{ .name = "perfmon_start_08", .path = "tests/perfmon_start_08.zig" },
    .{ .name = "perfmon_start_09", .path = "tests/perfmon_start_09.zig" },
    .{ .name = "perfmon_stop_01", .path = "tests/perfmon_stop_01.zig" },
    .{ .name = "perfmon_stop_02", .path = "tests/perfmon_stop_02.zig" },
    .{ .name = "perfmon_stop_03", .path = "tests/perfmon_stop_03.zig" },
    .{ .name = "perfmon_stop_04", .path = "tests/perfmon_stop_04.zig" },
    .{ .name = "perfmon_stop_05", .path = "tests/perfmon_stop_05.zig" },
    .{ .name = "perfmon_stop_06", .path = "tests/perfmon_stop_06.zig" },
    .{ .name = "port_io_virtualization_01", .path = "tests/port_io_virtualization_01.zig" },
    .{ .name = "port_io_virtualization_02", .path = "tests/port_io_virtualization_02.zig" },
    .{ .name = "port_io_virtualization_03", .path = "tests/port_io_virtualization_03.zig" },
    .{ .name = "port_io_virtualization_04", .path = "tests/port_io_virtualization_04.zig" },
    .{ .name = "port_io_virtualization_05", .path = "tests/port_io_virtualization_05.zig" },
    .{ .name = "port_io_virtualization_06", .path = "tests/port_io_virtualization_06.zig" },
    .{ .name = "port_io_virtualization_07", .path = "tests/port_io_virtualization_07.zig" },
    .{ .name = "port_io_virtualization_08", .path = "tests/port_io_virtualization_08.zig" },
    .{ .name = "port_io_virtualization_09", .path = "tests/port_io_virtualization_09.zig" },
    .{ .name = "port_io_virtualization_10", .path = "tests/port_io_virtualization_10.zig" },
    .{ .name = "port_io_virtualization_11", .path = "tests/port_io_virtualization_11.zig" },
    .{ .name = "priority_01", .path = "tests/priority_01.zig" },
    .{ .name = "priority_02", .path = "tests/priority_02.zig" },
    .{ .name = "priority_03", .path = "tests/priority_03.zig" },
    .{ .name = "priority_04", .path = "tests/priority_04.zig" },
    .{ .name = "priority_05", .path = "tests/priority_05.zig" },
    .{ .name = "priority_06", .path = "tests/priority_06.zig" },
    .{ .name = "priority_07", .path = "tests/priority_07.zig" },
    .{ .name = "priority_08", .path = "tests/priority_08.zig" },
    .{ .name = "recv_01", .path = "tests/recv_01.zig" },
    .{ .name = "recv_02", .path = "tests/recv_02.zig" },
    .{ .name = "recv_03", .path = "tests/recv_03.zig" },
    .{ .name = "recv_04", .path = "tests/recv_04.zig" },
    .{ .name = "recv_05", .path = "tests/recv_05.zig" },
    .{ .name = "recv_06", .path = "tests/recv_06.zig" },
    .{ .name = "recv_07", .path = "tests/recv_07.zig" },
    .{ .name = "recv_08", .path = "tests/recv_08.zig" },
    .{ .name = "remap_01", .path = "tests/remap_01.zig" },
    .{ .name = "remap_02", .path = "tests/remap_02.zig" },
    .{ .name = "remap_03", .path = "tests/remap_03.zig" },
    .{ .name = "remap_04", .path = "tests/remap_04.zig" },
    .{ .name = "remap_05", .path = "tests/remap_05.zig" },
    .{ .name = "remap_06", .path = "tests/remap_06.zig" },
    .{ .name = "remap_07", .path = "tests/remap_07.zig" },
    .{ .name = "remap_08", .path = "tests/remap_08.zig" },
    .{ .name = "remap_09", .path = "tests/remap_09.zig" },
    .{ .name = "reply_01", .path = "tests/reply_01.zig" },
    .{ .name = "reply_02", .path = "tests/reply_02.zig" },
    .{ .name = "reply_03", .path = "tests/reply_03.zig" },
    .{ .name = "reply_04", .path = "tests/reply_04.zig" },
    .{ .name = "reply_05", .path = "tests/reply_05.zig" },
    .{ .name = "reply_06", .path = "tests/reply_06.zig" },
    .{ .name = "reply_07", .path = "tests/reply_07.zig" },
    .{ .name = "reply_transfer_01", .path = "tests/reply_transfer_01.zig" },
    .{ .name = "reply_transfer_02", .path = "tests/reply_transfer_02.zig" },
    .{ .name = "restart_semantics_01", .path = "tests/restart_semantics_01.zig" },
    .{ .name = "restart_semantics_02", .path = "tests/restart_semantics_02.zig" },
    .{ .name = "restart_semantics_03", .path = "tests/restart_semantics_03.zig" },
    .{ .name = "restart_semantics_04", .path = "tests/restart_semantics_04.zig" },
    .{ .name = "restart_semantics_05", .path = "tests/restart_semantics_05.zig" },
    .{ .name = "restart_semantics_06", .path = "tests/restart_semantics_06.zig" },
    .{ .name = "restart_semantics_07", .path = "tests/restart_semantics_07.zig" },
    .{ .name = "restart_semantics_08", .path = "tests/restart_semantics_08.zig" },
    .{ .name = "restrict_01", .path = "tests/restrict_01.zig" },
    .{ .name = "restrict_02", .path = "tests/restrict_02.zig" },
    .{ .name = "restrict_03", .path = "tests/restrict_03.zig" },
    .{ .name = "restrict_04", .path = "tests/restrict_04.zig" },
    .{ .name = "restrict_05", .path = "tests/restrict_05.zig" },
    .{ .name = "restrict_06", .path = "tests/restrict_06.zig" },
    .{ .name = "restrict_07", .path = "tests/restrict_07.zig" },
    .{ .name = "revoke_01", .path = "tests/revoke_01.zig" },
    .{ .name = "revoke_02", .path = "tests/revoke_02.zig" },
    .{ .name = "revoke_03", .path = "tests/revoke_03.zig" },
    .{ .name = "revoke_04", .path = "tests/revoke_04.zig" },
    .{ .name = "revoke_05", .path = "tests/revoke_05.zig" },
    .{ .name = "revoke_06", .path = "tests/revoke_06.zig" },
    .{ .name = "self_01", .path = "tests/self_01.zig" },
    .{ .name = "self_02", .path = "tests/self_02.zig" },
    .{ .name = "self_handle_01", .path = "tests/self_handle_01.zig" },
    .{ .name = "snapshot_01", .path = "tests/snapshot_01.zig" },
    .{ .name = "snapshot_02", .path = "tests/snapshot_02.zig" },
    .{ .name = "snapshot_03", .path = "tests/snapshot_03.zig" },
    .{ .name = "snapshot_04", .path = "tests/snapshot_04.zig" },
    .{ .name = "snapshot_05", .path = "tests/snapshot_05.zig" },
    .{ .name = "snapshot_06", .path = "tests/snapshot_06.zig" },
    .{ .name = "snapshot_07", .path = "tests/snapshot_07.zig" },
    .{ .name = "snapshot_08", .path = "tests/snapshot_08.zig" },
    .{ .name = "snapshot_09", .path = "tests/snapshot_09.zig" },
    .{ .name = "snapshot_10", .path = "tests/snapshot_10.zig" },
    .{ .name = "snapshot_11", .path = "tests/snapshot_11.zig" },
    .{ .name = "suspend_01", .path = "tests/suspend_01.zig" },
    .{ .name = "suspend_02", .path = "tests/suspend_02.zig" },
    .{ .name = "suspend_03", .path = "tests/suspend_03.zig" },
    .{ .name = "suspend_04", .path = "tests/suspend_04.zig" },
    .{ .name = "suspend_05", .path = "tests/suspend_05.zig" },
    .{ .name = "suspend_06", .path = "tests/suspend_06.zig" },
    .{ .name = "sync_01", .path = "tests/sync_01.zig" },
    .{ .name = "sync_02", .path = "tests/sync_02.zig" },
    .{ .name = "sync_03", .path = "tests/sync_03.zig" },
    .{ .name = "terminate_01", .path = "tests/terminate_01.zig" },
    .{ .name = "terminate_02", .path = "tests/terminate_02.zig" },
    .{ .name = "terminate_03", .path = "tests/terminate_03.zig" },
    .{ .name = "terminate_04", .path = "tests/terminate_04.zig" },
    .{ .name = "terminate_05", .path = "tests/terminate_05.zig" },
    .{ .name = "terminate_06", .path = "tests/terminate_06.zig" },
    .{ .name = "terminate_07", .path = "tests/terminate_07.zig" },
    .{ .name = "terminate_08", .path = "tests/terminate_08.zig" },
    .{ .name = "timer_arm_01", .path = "tests/timer_arm_01.zig" },
    .{ .name = "timer_arm_02", .path = "tests/timer_arm_02.zig" },
    .{ .name = "timer_arm_03", .path = "tests/timer_arm_03.zig" },
    .{ .name = "timer_arm_04", .path = "tests/timer_arm_04.zig" },
    .{ .name = "timer_arm_05", .path = "tests/timer_arm_05.zig" },
    .{ .name = "timer_arm_06", .path = "tests/timer_arm_06.zig" },
    .{ .name = "timer_arm_07", .path = "tests/timer_arm_07.zig" },
    .{ .name = "timer_arm_08", .path = "tests/timer_arm_08.zig" },
    .{ .name = "timer_arm_09", .path = "tests/timer_arm_09.zig" },
    .{ .name = "timer_arm_10", .path = "tests/timer_arm_10.zig" },
    .{ .name = "timer_cancel_01", .path = "tests/timer_cancel_01.zig" },
    .{ .name = "timer_cancel_02", .path = "tests/timer_cancel_02.zig" },
    .{ .name = "timer_cancel_03", .path = "tests/timer_cancel_03.zig" },
    .{ .name = "timer_cancel_04", .path = "tests/timer_cancel_04.zig" },
    .{ .name = "timer_rearm_01", .path = "tests/timer_rearm_01.zig" },
    .{ .name = "timer_rearm_02", .path = "tests/timer_rearm_02.zig" },
    .{ .name = "timer_rearm_03", .path = "tests/timer_rearm_03.zig" },
    .{ .name = "unmap_01", .path = "tests/unmap_01.zig" },
    .{ .name = "unmap_02", .path = "tests/unmap_02.zig" },
    .{ .name = "unmap_03", .path = "tests/unmap_03.zig" },
    .{ .name = "unmap_04", .path = "tests/unmap_04.zig" },
    .{ .name = "unmap_05", .path = "tests/unmap_05.zig" },
    .{ .name = "unmap_06", .path = "tests/unmap_06.zig" },
    .{ .name = "unmap_07", .path = "tests/unmap_07.zig" },
    .{ .name = "unmap_08", .path = "tests/unmap_08.zig" },
    .{ .name = "unmap_09", .path = "tests/unmap_09.zig" },
    .{ .name = "unmap_10", .path = "tests/unmap_10.zig" },
    .{ .name = "unmap_11", .path = "tests/unmap_11.zig" },
    .{ .name = "unmap_12", .path = "tests/unmap_12.zig" },
    .{ .name = "unmap_guest_01", .path = "tests/unmap_guest_01.zig" },
    .{ .name = "unmap_guest_02", .path = "tests/unmap_guest_02.zig" },
    .{ .name = "unmap_guest_03", .path = "tests/unmap_guest_03.zig" },
    .{ .name = "unmap_guest_04", .path = "tests/unmap_guest_04.zig" },
    .{ .name = "unmap_guest_05", .path = "tests/unmap_guest_05.zig" },
    .{ .name = "vm_inject_irq_01", .path = "tests/vm_inject_irq_01.zig" },
    .{ .name = "vm_inject_irq_02", .path = "tests/vm_inject_irq_02.zig" },
    .{ .name = "vm_inject_irq_03", .path = "tests/vm_inject_irq_03.zig" },
    .{ .name = "vm_inject_irq_04", .path = "tests/vm_inject_irq_04.zig" },
    .{ .name = "vm_inject_irq_05", .path = "tests/vm_inject_irq_05.zig" },
    .{ .name = "vm_set_policy_01", .path = "tests/vm_set_policy_01.zig" },
    .{ .name = "vm_set_policy_02", .path = "tests/vm_set_policy_02.zig" },
    .{ .name = "vm_set_policy_03", .path = "tests/vm_set_policy_03.zig" },
    .{ .name = "vm_set_policy_04", .path = "tests/vm_set_policy_04.zig" },
    .{ .name = "vm_set_policy_05", .path = "tests/vm_set_policy_05.zig" },
    .{ .name = "vm_set_policy_07", .path = "tests/vm_set_policy_07.zig" },
    .{ .name = "vm_set_policy_08", .path = "tests/vm_set_policy_08.zig" },
    .{ .name = "vm_set_policy_09", .path = "tests/vm_set_policy_09.zig" },
    .{ .name = "yield_01", .path = "tests/yield_01.zig" },
    .{ .name = "yield_02", .path = "tests/yield_02.zig" },
    .{ .name = "yield_03", .path = "tests/yield_03.zig" },
    .{ .name = "yield_04", .path = "tests/yield_04.zig" },
};

fn buildTestElf(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    lib_mod: *std.Build.Module,
    name: []const u8,
    src_path: []const u8,
) std.Build.LazyPath {
    const app_mod = b.createModule(.{
        .root_source_file = b.path(src_path),
        .target = target,
        .optimize = .ReleaseSmall,
        .pic = true,
        .omit_frame_pointer = true,
    });
    app_mod.addImport("lib", lib_mod);

    const start_mod = b.createModule(.{
        .root_source_file = .{ .cwd_relative = "libz/start.zig" },
        .target = target,
        .optimize = .ReleaseSmall,
        .pic = true,
        .omit_frame_pointer = true,
    });
    start_mod.addImport("lib", lib_mod);
    start_mod.addImport("app", app_mod);

    const exe = b.addExecutable(.{
        .name = name,
        .root_module = start_mod,
        .linkage = .static,
    });
    exe.pie = true;
    exe.entry = .{ .symbol_name = "_start" };
    exe.setLinkerScript(b.path("linker.ld"));

    return exe.getEmittedBin();
}

pub fn build(b: *std.Build) void {
    const target = b.resolveTargetQuery(.{
        .cpu_arch = .x86_64,
        .os_tag = .freestanding,
    });

    const lib_mod = b.createModule(.{
        .root_source_file = .{ .cwd_relative = "libz/lib.zig" },
        .target = target,
        .optimize = .ReleaseSmall,
        .pic = true,
        .omit_frame_pointer = true,
    });
    // self-reference so libz files can `@import("lib")`
    lib_mod.addImport("lib", lib_mod);

    const embedded_wf = b.addWriteFiles();
    var test_elfs: [test_entries.len]std.Build.LazyPath = undefined;
    for (test_entries, 0..) |t, i| {
        test_elfs[i] = buildTestElf(b, target, lib_mod, t.name, t.path);
        _ = embedded_wf.addCopyFile(test_elfs[i], b.fmt("{s}.elf", .{t.name}));
    }

    // Generate a manifest module surfacing the embedded ELFs as a
    // slice the primary iterates. Manifest order = spawn order.
    var manifest = std.array_list.Managed(u8).init(b.allocator);
    defer manifest.deinit();
    manifest.appendSlice(
        \\pub const Entry = struct {
        \\    name: []const u8,
        \\    bytes: []const u8,
        \\};
        \\
        \\pub const manifest = [_]Entry{
        \\
    ) catch unreachable;
    for (test_entries) |t| {
        manifest.writer().print(
            "    .{{ .name = \"{s}\", .bytes = @embedFile(\"{s}.elf\") }},\n",
            .{ t.name, t.name },
        ) catch unreachable;
    }
    manifest.appendSlice("};\n") catch unreachable;
    const manifest_src = embedded_wf.add("embedded_tests.zig", manifest.items);

    const embedded_tests_mod = b.createModule(.{
        .root_source_file = manifest_src,
        .target = target,
        .optimize = .ReleaseSmall,
    });

    const app_mod = b.createModule(.{
        .root_source_file = b.path("runner/primary.zig"),
        .target = target,
        .optimize = .ReleaseSmall,
        .pic = true,
        .omit_frame_pointer = true,
    });
    app_mod.addImport("lib", lib_mod);
    app_mod.addImport("embedded_tests", embedded_tests_mod);

    const start_mod = b.createModule(.{
        .root_source_file = .{ .cwd_relative = "libz/start.zig" },
        .target = target,
        .optimize = .ReleaseSmall,
        .pic = true,
        .omit_frame_pointer = true,
    });
    start_mod.addImport("lib", lib_mod);
    start_mod.addImport("app", app_mod);

    const exe = b.addExecutable(.{
        .name = "root_service",
        .root_module = start_mod,
        .linkage = .static,
    });
    exe.pie = true;
    exe.entry = .{ .symbol_name = "_start" };
    exe.setLinkerScript(b.path("linker.ld"));

    const install = b.addInstallFile(exe.getEmittedBin(), "../bin/root_service.elf");
    b.getInstallStep().dependOn(&install.step);

    // Install the individual test ELFs alongside for inspection.
    for (test_entries, 0..) |t, i| {
        const path = b.fmt("../bin/{s}.elf", .{t.name});
        const inst = b.addInstallFile(test_elfs[i], path);
        b.getInstallStep().dependOn(&inst.step);
    }
}
