pub const SyscallNum = enum(u64) {
    ack = 26,
    acquire_ecs = 5,
    acquire_vars = 6,
    affinity = 12,
    bind_event_route = 36,
    clear_event_route = 37,
    create_capability_domain = 4,
    create_execution_context = 7,
    create_page_frame = 25,
    create_port = 33,
    create_var = 17,
    create_vcpu = 28,
    create_virtual_machine = 27,
    delete = 1,
    futex_wait_change = 44,
    futex_wait_val = 43,
    futex_wake = 45,
    idc_read = 23,
    idc_write = 24,
    info_cores = 51,
    info_system = 50,
    map_guest = 29,
    map_mmio = 19,
    map_pf = 18,
    perfmon_info = 13,
    perfmon_read = 15,
    perfmon_start = 14,
    perfmon_stop = 16,
    power_reboot = 53,
    power_screen_off = 55,
    power_set_freq = 56,
    power_set_idle = 57,
    power_shutdown = 52,
    power_sleep = 54,
    priority = 11,
    random = 49,
    recv = 35,
    remap = 21,
    reply = 38,
    reply_transfer = 39,
    restrict = 0,
    revoke = 2,
    self = 8,
    snapshot = 22,
    @"suspend" = 34,
    sync = 3,
    terminate = 9,
    time_getwall = 47,
    time_monotonic = 46,
    time_setwall = 48,
    timer_arm = 40,
    timer_cancel = 42,
    timer_rearm = 41,
    unmap = 20,
    unmap_guest = 30,
    vm_inject_irq = 32,
    vm_set_policy = 31,
    yield = 10,
};

pub fn dispatch(caller: *anyopaque, syscall_word: u64, args: []const u64) i64 {
    _ = caller;
    _ = syscall_word;
    _ = args;
    // TODO: dispatch table
    return 0;
}
